name: Publish
on: 
  push:
    branches:
      - master
      - main

jobs:

  publish:
    name: Publish
    runs-on: ubuntu-latest
     
    steps:

      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: latest
      
      - name: Setup cache
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
            ${{ runner.os }}-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          greater-version-only: true
          access: public

      # - name: TODO => Notification
      #   run: echo 'TODO => Build a Notification pipeline'
  
  # clean:
  #   runs-on: ubuntu-latest
  #   needs: publish
      
  #   steps:
       
  #     - name: Some
  #       run: echo "TODO => Cleaning up"
        